### ISSUE TITLE
Using the inventory is very slow

### ISSUE THREAD

**Issue by neuromancer** [cyxx/f2bgl#1]
When i press the inventory key (i) and enter into the inventory, the game starts to be very slow (almost no response), until i get out of that screen.

**Comment by cyxx** [comment]
fixed with c4a05b4c87

**Comment by neuromancer** [comment]
Thanks!, btw, is this project starting to be active again or just a bug fixing round?

**Comment by cyxx** [comment]
the latter, just a few bug fixes...
