### ISSUE TITLE
f2b

### ISSUE THREAD

**Issue by markourb** [cyxx/f2bgl#13]
I hope that works  ffmpeg and other  https://github.com/Mindwerks/wildmidi/releases/download/wildmidi-0.4.2/wildmidi-0.4.2-win64.zip you send  and can you send me an attachment dll in rar or zip
libwildmidi.dll please if you want please help me I really want that fade to black to work i played a long time ago

**Comment by markourb** [comment]
it sed this c:\fade\libwildmidi.dll is either not designed to run on windows or it contains error try installing medija or contact your system administrator of the software vendor for support error status 0xc000035a please help me

**Comment by cyxx** [comment]
I don't have access to a win64 machine to check this.
Can you try with the dlls from https://www.dropbox.com/s/vs6pg5z310riybq/f2bgl-0.3.0-win32-dll.zip?dl=0 ? This is what I use on win32.

**Comment by cyxx** [comment]
Solved in #12
