### ISSUE TITLE
Master won't compile - missing lib.

### ISSUE THREAD

**Issue by gonzalezfacundo** [cyxx/f2bgl#5]
Hi,
I 've downloaded you master-branch and when I try to compile with Mingw32 I get some errors. I solved it including "string.h" in your main.cpp
¿Could you please fix it? Nice job and keep working :D 

The output was: 

c:\f2bgl-master>make
g++ -g -O -Wall -Wuninitialized -Wno-sign-compare -MMD  -IC:\ming_dev_lib\includ
e\SDL2 -LC:\ming_dev_lib\lib   -c -o main.o main.cpp
main.cpp: In function 'void setupKeyMap()':
main.cpp:34:52: error: 'memset' was not declared in this scope
  memset(gKeyScancodeMap, 0, sizeof(gKeyScancodeMap));
                                                    ^
main.cpp: In function 'void setupAudio(GameStub*)':
main.cpp:93:37: error: 'memset' was not declared in this scope
  memset(&desired, 0, sizeof(desired));
                                     ^
<builtin>: recipe for target 'main.o' failed
make: *** [main.o] Error

**Comment by cyxx** [comment]
should be fixed with f4abcb6c
