### ISSUE TITLE
Support case sensitive file systems

### ISSUE THREAD

**Issue by neuromancer** [cyxx/f2bgl#7]
Hi,

f2bgl does not seems to be working out-of-the-box in case senstivie file systems like Linux. I'm testing it using [this iso image from Archive.org](https://archive.org/details/Fade_to_Black_1995_Electronic_Arts_M3_). Is it possible to support such platforms?

Thanks!

**Comment by cyxx** [comment]
Hi,

There is some code to try lower / uppercase filenames if opening fails. This does not cover mixed case filenames or directories, though.

Can you please attach the stdout/stderr output of f2bgl with this version ? I would also like to confirm the directory structure.

Thanks

**Comment by neuromancer** [comment]
If you mount the iso and try to use f2bgl, it won't find any datafile:


> ./f2bgl --datapath=F2B_F101
> WARNING: Unable to find datafiles!

If you rename the directories to DATA, DATA/SOUND, etc, it won't find the files for level1. Also, find attached the [list of files per directory](https://github.com/cyxx/f2bgl/files/912856/f2b.txt) after mount the iso in ArchLinux, it could be useful.

Thanks!

**Comment by cyxx** [comment]
Can you have a try at fcbf8d0897 ?

**Comment by neuromancer** [comment]
Still not working :(

> ERROR: Unable to open 'level1.snt'!

I traced f2bgl using ltrace. Find [attached](https://github.com/cyxx/f2bgl/files/915080/trace.txt.gz) the compressed trace (it's a text file after all). It should be useful to know what file is actually reading.

**Comment by cyxx** [comment]
Looks like the problem is related to the directory structure, both 'voice' and 'text' are under 'data'.
This is different from the installed version, where 'voice' and 'text' are at the same level as 'data'. Will see if it is easy to support both structures.

**Comment by neuromancer** [comment]
If you move 'voice' and 'text', it seems to work.

**Comment by cyxx** [comment]
Yes, this is the supported structure (as detailed in the README).
Let's see if the CDROM structure can be detected, as I assume you cannot easily move/rename directories from a mounted .iso.

**Comment by cyxx** [comment]
Can you try dcd4e376e30270f5ac if it helps ?

**Comment by neuromancer** [comment]
Its working now. Thanks!
